### ISSUE TITLE
Use windows-compatible file names

### ISSUE THREAD

**Issue by timhoffm** [jlaurens/synctex#13]
The repository contains two files having `\includegraphics` in their name. `\` is not a valid character for file names on windows. This produces some problems when checking out the repository on windows.

The problematic files are:

synctex test files/test files/[pdftex] Invalid SyncTeX file with \includegraphics.html
synctex test files/test files/[pdftex] Invalid SyncTeX file with \includegraphics.webarchive

Please rename them.

**Comment by jlaurens** [comment]
Fixed in 1.21
