### ISSUE TITLE
synctex_display_query() returns less result since 1.19

### ISSUE THREAD

**Issue by timhoffm** [jlaurens/synctex#15]
Using synctex in a pdf viewer for highlighting text. Since version 1.19 `synctex_display_query()` returns only one result, whereas there have been multiple results in earlier versions.

Example (compiled with recent lualatex from MikTeX):

```
\documentclass{article}
\usepackage[english]{babel}
\usepackage{lipsum}

\begin{document}

\lipsum[3]

\lipsum[4]

\lipsum[5]

\end{document}
```

Performing `synctex_display_query()` on the line `\lipsum[3]` returns only one result in v1.19/v1.20:

![grafik](https://user-images.githubusercontent.com/2836374/31867573-8cedf656-b792-11e7-9490-6bba708b4892.png)

With version 1.18 there were 11 results:

![grafik](https://user-images.githubusercontent.com/2836374/31867730-a442fd90-b794-11e7-89e7-f2408f77b2cc.png)

Note: Both examples were performed with the same synctex.gz file. Only the client code of the viewer was changed.

**Comment by jlaurens** [comment]
The filtering algorithm is a bit aggressive
Reverted to the 1.18 level.
Merged in 2017 master branch
