### ISSUE TITLE
Memory leak when opening files

### ISSUE THREAD

**Issue by stloeffler** [jlaurens/synctex#49]
When calling `synctex_scanner_new_with_output_file` with `parse=1`, first a reader is initialized by a call to `synctex_reader_init_with_output_file`. This allocates a buffer of size `SYNCTEX_BUFFER_SIZE` ([synctex_parser.c#L769-L773](https://github.com/jlaurens/synctex/blob/c11fe00dbdc6423a0e54d4e531563be645f78679/synctex_parser.c#L769-L773), accessible via `reader->start`. Then, `synctex_scanner_parse` is called which again allocates the same buffer ([synctex_parser.c#L6107](https://github.com/jlaurens/synctex/blob/c11fe00dbdc6423a0e54d4e531563be645f78679/synctex_parser.c#L6107)) without deallocating the previous memory, leading to the leak.

I see two possible ways to fix this:
1) If the buffer is guaranteed to not be deallocated/reallocated with a different size during the lifetime of the reader, the second allocation could just be removed
2) If that guarantee is not available, the buffer should be properly dellocated/reallocated as necessary in `synctex_scanner_parse` (or not be allocated in `synctex_reader_init_with_output_file` in the first place, but that might lead to all sorts of other problems with code expecting the buffer to always be valid)

**Comment by aminophen** [comment]
Thanks for the update, installed on [r65582](https://www.tug.org/svn/texlive?view=revision&revision=65582) with other changes.
