### ISSUE TITLE
Stable release and branches

### ISSUE THREAD

**Issue by timhoffm** [jlaurens/synctex#6]
What is the current stable version?

There are branches: master, 2017 and 2017-1.20.

It would help if you could briefly describe their purposes in README.md. I was using 2017 but noticed severe problems on windows. I don't know if it's still worth posting bugs/pull requests for this branch.

Thanks for developing synctex further.

**Comment by jlaurens** [comment]
2017 is the stable version
2017-1.20 is the WIP.
I will put this in the .md
